# Generated by Django 4.2.13 on 2024-08-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("intime", "In time"), ("delayed", "Delayed")],
                        default="",
                        max_length=10,
                    ),
                ),
                ("total_hours_worked", models.FloatField(null=True)),
                ("overtime_status", models.CharField(default="", max_length=50)),
            ],
        ),
    ]
