# Generated by Django 4.2.13 on 2024-07-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="address",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="email",
        ),
        migrations.AddField(
            model_name="employee",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="overtime_status",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="employee",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[("intime", "In time"), ("delayed", "Delayed")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="total_hours_worked",
            field=models.FloatField(null=True),
        ),
    ]
